### ISSUE TITLE
zend_hash_index_exists causes a seg fault on php 7

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1249]
OS: Ubuntu 14.04
PHP: 7.0.5 with Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, dom, fileinfo, filter, gettext, hash, json, mbstring, mcrypt, SPL, session, pcntl, standard, PDO, mysqlnd, pdo_pgs
ql, pdo_sqlite, pgsql, apcu, posix, readline, Reflection, pdo_mysql, shmop, SimpleXML, sockets, mysqli, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, test, phalcon, 
apc(using apcu_bc), Phar, curl, mongodb

**This problem is happening only on non-debug version. On debug version there is Exception throwned instead:**

https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/mvc/model/query.zep#L2466

Seg fault is caused when doing any `Model::findFirst()` on phalcon on database MySQL. I guess its actually true when doing any select.

I will try to reproduce error without relaying on phalcon when i have time and will figure out what is causing a problem exactly.

There is stack trace: http://pastebin.com/vt0Z6ETX

There are some code to reproduce it on phalcon:

``` php
<?php
class Avatar extends \Phalcon\Mvc\Model
{
    /**
     * @var
     */
    protected $id;

    /**
     * @var
     */
    protected $name;

    protected $user;
}

$di = new \Phalcon\Di\FactoryDefault();

$di->set(
    'db',
    function () {
        $config = [
            'adapter' => 'Mysql',
            'host' => 'localhost',
            'username' => 'root',
            'password' => '',
            'dbname' => 'test_hasone',
            'port' => 3306,
        ];
        $adapter = '\Phalcon\Db\Adapter\Pdo\\' . $config['adapter'];
        $connection = new $adapter($config);

        return $connection;
    }
);

$avatar = Avatar::findFirst(); // this is causing crash on non-debug or exception on debug
```

**Comment by andresgutierrez** [comment]
The PHQL parser is not fully ported to php7, so I think this might cause segfaults, I wouldn't blame Zephir for this.

**Comment by Jurigag** [comment]
@andresgutierrez 

Okay. So this is phalcon related for 100% ? Then im closing issue for now when i will check out that's it surely phql parser.

**Comment by andresgutierrez** [comment]
I'm currently porting parsers in Phalcon to a new structure, hopefully it will provide us a more safe php7 execution.

**Comment by Jurigag** [comment]
Okay. If someone will reproduce it without relaying on phalcon then mention me here and i will reopen issue. Also mention me in commit with parsers done so i can run tests and check them if there is any problem further.

**Comment by Jurigag** [comment]
Okay did some simple digging. Here https://github.com/phalcon/cphalcon/blob/2.1.x/ext/phalcon/mvc/model/query/parser.c#L303 list has 0 elements on php 7.0.5 and 2 on 5.6.19. So im guessing there is some problem with `phql_` https://github.com/phalcon/cphalcon/blob/2.1.x/ext/phalcon/mvc/model/query/parser.c#L2789 or `phql_alloc` https://github.com/phalcon/cphalcon/blob/2.1.x/ext/phalcon/mvc/model/query/parser.c#L1141 Don't know c enough to figure out what is going on.

What you mean porting parsers to a new structure ? You mean to zephir ? @andresgutierrez

Some fix would be nice until it will be realased.

**Comment by andresgutierrez** [comment]
I mean this: https://github.com/phalcon/zephir/pull/1248, create a specialized parser for php5 and other for php7 in phql/volt/annotations. I already started this work on this branch, if you want to take a look: https://github.com/phalcon/cphalcon/tree/php7-parsers

**Comment by Jurigag** [comment]
So i would need to merge php7-parsers and 2.1.x and it could possibly work ? Or it's already 2.1.x base branch ?

**Comment by andresgutierrez** [comment]
Not now, maybe in a couple of days

**Comment by Jurigag** [comment]
Okay then. I will be waiting for it to check if it fix current problems(i guess yes)

Well this is refractor only ? Or something iis broken in current phql parser for php7 ?

**Comment by Jurigag** [comment]
@andresgutierrez 

Also i have a question are those new parsers are gonna fix problems with volt setVar etc in php7 ? Beacause right now to access vars in volt template in view we have to access view object like {{ view.someVar }}

**Comment by andresgutierrez** [comment]
No, that's another issue, `create_symbol_table` optimizer must be fixed in order to make that work.

**Comment by Jurigag** [comment]
So it should be next in thing in the list after those parsers for php7 i think because it's pretty much crucial option, i can't help though because don't know c.

**Comment by Jurigag** [comment]
@andresgutierrez 

Just info - i checked latest php7-parsers, saw you did something with phql - but the seg fault is still the same.
