### ISSUE TITLE
Access to undeclared static property

### ISSUE THREAD

**Issue by xqkeji** [zephir-lang/zephir#1530]
When ajax request more than 3 times, there will be "Access to undeclared static property"
E.g
```zep
namespace XqKeji;

class Di
{
	private static _default;

	public static function getInstance()
	{
		var di
		let di = self::_default;

		if !di {
			let di = new self();
			let self::_default = di;
		}

		return self::_default;
	}
}
```

```zep
class app
{
	public function __construct()
	{
		var di;
		let di = \XqKeji\Di::getInstance();
	}
}
```
Test:

```php
<?php
$App = new App();

```
 in window php7.0 ts

**Comment by xqkeji** [comment]
`zephir_read_static_property_ce(&di, xqkeji_di_ce, SL("_default"), PH_NOISY_CC);`

Does php7 do not need TSRMLS_CC

**Comment by xqkeji** [comment]
As long as the load is high, will appear "Access to undeclared static property"。

**Comment by Jurigag** [comment]
Add that this happens only on php apache module, on cli or fpm it works fine and without issues.

**Comment by sergeyklay** [comment]
Refs:
* https://github.com/phalcon/cphalcon/issues/12056
* https://github.com/phalcon/cphalcon/issues/12803
* https://github.com/phalcon/cphalcon/issues/12791
* https://github.com/phalcon/cphalcon/issues/12110
* https://github.com/phalcon/cphalcon/issues/12065
* https://github.com/phalcon/cphalcon/issues/12329

**Comment by sergeyklay** [comment]
@sjinks Could you please take a look

**Comment by hakimio** [comment]
@sjinks It's rather important that you take a look at this bug as soon as possible, because it prevents usage of thread-safe extension on any platform, not only windows. So, it's no longer possible to use phalcon with pthreads and similar stuff which actually requires thread safety.

**Comment by afbora** [comment]
I got this error on Phalcon 3.2.0 today.
Its gone when i refresh the page 😕

**Comment by sergeyklay** [comment]
@php318 Could you change your code to:
```diff
namespace XqKeji;

class Di
{
	private static _default;

	public static function getInstance()
	{
-		var di
-		let di = self::_default;

-		if !di {
+		if typeof self::_default !== "object" {
-			let di = new self();
-			let self::_default = di;
+			let self::_default = new self();
		}

		return self::_default;
	}
}
```

and test it

**Comment by sergeyklay** [comment]
/ cc: @hakimio, @afbora

**Comment by Jurigag** [comment]
@sergeyklay i saw you are doing some tests with this, are you sure you are doing it on TS php? Beacause as i remember this is main issue, but not sure.

**Comment by xqkeji** [comment]
@sergeyklay 
I  test it, the error still exists.

**Comment by mattysj66** [comment]
Hey guys, what was the outcome to this bug?

I'm encountering the same issue on Windows and Apache 2.4 running PHP 7.1.1 and Phalcon 3.2.4

**Comment by hakimio** [comment]
@mattratcliffe86 Use nginx + php-fpm instead of Apache. There are some issues with thread safety of the extension.
https://www.progressivethink.in/on/administration/and/setup-nginx-and-php-on-windows/
https://docs.phalconphp.com/en/latest/webserver-setup#nginx

**Comment by mattysj66** [comment]
@hakimio Thanks for that.

So this is specifically affecting the thread safe extension for Apache, just on Windows or is it Linux too?

**Comment by hakimio** [comment]
@mattratcliffe86 It's effecting both windows and linux thread-safe extensions.

**Comment by Pilsenerek** [comment]
I have the same problem:
Phalcon 3.3.1
System Win7
PHP:
- version 7.2
- tread safe enabled
- architecture x86
- compiler MSVC15

It occurs especially when there are many requests in the same time or fast one by one in row.

**Comment by hakimio** [comment]
@Pilsenerek 
Its's an old well-known issue. See the following: https://github.com/phalcon/cphalcon/issues/12056

**Comment by sergeyklay** [comment]
I'm going to solve this issue so I need code to reproduce guys. Could someone provide a worked (badly) example?

**Comment by hakimio** [comment]
@sergeyklay It's rather easy to reproduce the issue. You just need to run phalcon Thread-Safe extension with Apache on Windows (some people reported the issue on Linux as well but I've never tried running Phalcon TS on Linux personally) and then just make a large number of parallel requests (shouldn't need more than a 100) to a single end-point which does some simulated work ("usleep(100000)" should work just fine).

**Comment by sergeyklay** [comment]
I need to locate problem. So it is too complex to use full framework to debug this. Actually I need an example as small as possible

**Comment by hakimio** [comment]
Maybe then create a simple Zephir extension, compile it with TS and use pthreads to check if it is actually thread safe?

**Comment by mattysj66** [comment]
@sergeyklay 

Quick and dirty way to reproduce the error...
[ptest.zip](https://github.com/phalcon/zephir/files/1772923/ptest.zip)

I've created a controller 'reload' which just reloads the page a given number of times and increments the value in the url segment by 1 each time. I'm redirecting, which is what I did when I first encountered the problem. Same thing occurs when you use $response->redirect() (\Phalcon\Http\Response) or the native header() function in PHP.

PHP Fatal error:  Uncaught Error: Access to undeclared static property Phalcon\\Di::$_default in index.php on line 10

Line 10 happens to be $di = new FactoryDefault();

**Comment by stijn1989** [comment]
I still have this error (Phalcon 3.3.2 with PHP7.2) when the app performs two ajax requests at the same time. If I perform the first ajax call and 500ms later I call the second ajax, it works.

**Comment by Jurigag** [comment]
@stijn1989 just read previous posts, it's because your php is working as thread safety extension. @sergeyklay wants to solve it so have fingers crossed.

**Comment by afbora** [comment]
I have still the issue on Phalcon version 3.4.1 🐛

**Comment by hakimio** [comment]
@afbora Well, nobody said the bug was fixed, did they?

**Comment by afbora** [comment]
@hakimio I know it's not fixed. I just wrote it to keep it up to date 👍

**Comment by sergeyklay** [comment]
Currently I'm working on PHP 7.3 support: https://github.com/phalcon/zephir/pull/1674. Next in my plans is https://github.com/phalcon/zephir/issues/1621. You will probably have to wait if no one will not fix this before.

**Comment by ismail0234** [comment]
Is there a valid solution?

**Comment by sergeyklay** [comment]
@dreamsxin It seems we need you here. Could you please take a look

**Comment by dreamsxin** [comment]
I can't  reproduce, 

> Ubuntu 16.04
> Zephir 0.11.10
> PHP 7.2.15 (cli) (built: Feb 19 2019 16:14:30) ( ZTS DEBUG )
> Phalcon v4.0.0-alpha.2 

```shell
ab -c 20 -n 200 http://localhost:8181/
```
Another test code:
```zephir
namespace Mytest;

class Di
{
	private static _default;

	public static function getInstance()
	{
		var di;
		let di = self::_default;

		if !di {
			let di = new self();
			let self::_default = di;
		}

		return self::_default;
	}
}

class App
{
	public function __construct()
	{
		var di;
		let di = Di::getInstance();
	}
}
```

Phalcon v3.4.0
```output
PHP Fatal error:  Declaration of Phalcon\Forms\Element::getAttribute(string $attribute, $defaultValue = NULL) must be compatible with Phalcon\Forms\ElementInterface::getAttribute($attribute, $defaultValue = NULL) in Unknown on line 0
...
```

**Comment by sergeyklay** [comment]
@dreamsxin You have to use Zephir 0.10.x for Phalcon 3.x and Zephir 0.11.x for Phalcon 4.x. This is why you get "PHP Fatal error" for Phalcon v3.4.0 using Zephir 0.11.x

Did you use Thread-Safe extension with Apache ? It is important here

**Comment by dreamsxin** [comment]
@sergeyklay I don't have an apache environment.

**Comment by sergeyklay** [comment]
@dreamsxin Is there any chance that you will be able to use a Docker or any VM?

**Comment by dreamsxin** [comment]
@sergeyklay I'm not sure that under Linux, libapache-mod-php uses thread safe, and my computer is too old. It would be great if you can test and get core dump.

**Comment by hakimio** [comment]
@dreamsxin you should be able to reproduce the issue with TS php-cli as well.

**Comment by dreamsxin** [comment]
@hakimio Can't reproduce, Previously tested in CLI

Ubuntu 16.04
Zephir 0.11.10
PHP 7.2.15 (cli) (built: Feb 19 2019 16:14:30) ( ZTS DEBUG )
Phalcon v4.0.0-alpha.2

**Comment by CameronHall** [comment]
@dreamsxin I managed to produce a dump. That's a pretty version produced by `DebugDiag Analysis 2`  that you'll need to open with a browser. 

If you need the `.dmp` let me know on Discord.

**Comment by dreamsxin** [comment]
I will feedback

**Comment by dreamsxin** [comment]
@CameronHall  Unfortunately, my computer is not Windows.
And the use of virtual machines (xp systems), as shown below

> DebugDiag Analysis cannot be performed against a 64-bit dump file from a 32-bit analysis machine. Please run the analysis on a 64-bit machine to get analysis details. 

I want to admire that the document is too big.

**Comment by CameronHall** [comment]
No worries. If you're okay with the HTML files from DebugDiag, I can generate them for the other dumps I send to you via email.

**Comment by CameronHall** [comment]
I sent @dreamsxin the dumps. I also sent him this stack trace.

```
KERNELBASE!wil::details::DebugBreak+2	  
php7ts_debug!zend_output_debug_string+a1 [c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend.c @ 1445]	  c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend.c @ 1445
php7ts_debug!php_error_cb+1027 [c:\php-sdk\phpmaster\vc15\x64\php-src\main\main.c @ 1218]	  c:\php-sdk\phpmaster\vc15\x64\php-src\main\main.c @ 1218
php7ts_debug!soap_error_handler+21c [c:\php-sdk\phpmaster\vc15\x64\php-src\ext\soap\soap.c @ 2129 + 3c]	  c:\php-sdk\phpmaster\vc15\x64\php-src\ext\soap\soap.c @ 2129 + 3c
php7ts_debug!zend_error_va_list+57c [c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend.c @ 1221 + 32]	  c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend.c @ 1221 + 32
php7ts_debug!zend_error_noreturn+48 [c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend.c @ 1343]	  c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend.c @ 1343
php7ts_debug!zend_timeout+bd [c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_execute_api.c @ 1162]	  c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_execute_api.c @ 1162
php7ts_debug!zend_interrupt_helper_SPEC+97 [c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_vm_execute.h @ 2076 + 7]	  c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_vm_execute.h @ 2076 + 7
php7ts_debug!ZEND_DO_ICALL_SPEC_RETVAL_UNUSED_HANDLER+2b4 [c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_vm_execute.h @ 596 + 5c]	  c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_vm_execute.h @ 596 + 5c
php7ts_debug!execute_ex+8d [c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_vm_execute.h @ 59739 + f]	  c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_vm_execute.h @ 59739 + f
php7ts_debug!zend_call_function+f1c [c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_execute_api.c @ 821]	  c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_execute_api.c @ 821
php7ts_debug!zephir_call_user_func_array_noex+160 [c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 8576]	  c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 8576
php7ts_debug!zephir_call_user_func_array+45 [c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 2856 + 14]	  c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 2856 + 14
php7ts_debug!zim_Phalcon_Dispatcher_callActionMethod+570 [c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 18413 + 17]	  c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 18413 + 17
php7ts_debug!zend_call_function+108b [c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_execute_api.c @ 835]	  c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_execute_api.c @ 835
php7ts_debug!zephir_call_user_function+6b2 [c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 8380 + 12]	  c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 8380 + 12
php7ts_debug!zephir_call_class_method_aparams+159 [c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 8516 + 5f]	  c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 8516 + 5f
php7ts_debug!zim_Phalcon_Dispatcher_dispatch+6f66 [c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 18083 + 14a]	  c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 18083 + 14a
php7ts_debug!zend_call_function+108b [c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_execute_api.c @ 835]	  c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_execute_api.c @ 835
php7ts_debug!zephir_call_user_function+6b2 [c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 8380 + 12]	  c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 8380 + 12
php7ts_debug!zephir_call_class_method_aparams+159 [c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 8516 + 5f]	  c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 8516 + 5f
php7ts_debug!zim_Phalcon_Mvc_Application_handle+4f17 [c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 84599 + 113]	  c:\php-sdk\phpmaster\vc15\x64\pecl\phalcon\phalcon.zep.c @ 84599 + 113
php7ts_debug!ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER+3e3 [c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_vm_execute.h @ 1033]	  c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_vm_execute.h @ 1033
php7ts_debug!execute_ex+8d [c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_vm_execute.h @ 59739 + f]	  c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_vm_execute.h @ 59739 + f
php7ts_debug!zend_execute+1eb [c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_vm_execute.h @ 63777]	  c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend_vm_execute.h @ 63777
php7ts_debug!zend_execute_scripts+10f [c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend.c @ 1497]	  c:\php-sdk\phpmaster\vc15\x64\php-src\zend\zend.c @ 1497
php7ts_debug!php_execute_script+7d5 [c:\php-sdk\phpmaster\vc15\x64\php-src\main\main.c @ 2590 + 2e]	  c:\php-sdk\phpmaster\vc15\x64\php-src\main\main.c @ 2590 + 2e
php7apache2_4!php_handler+83c [c:\php-sdk\phpmaster\vc15\x64\php-src\sapi\apache2handler\sapi_apache2.c @ 702]	  c:\php-sdk\phpmaster\vc15\x64\php-src\sapi\apache2handler\sapi_apache2.c @ 702
libhttpd!ap_run_handler+35	  
libhttpd!ap_invoke_handler+10f	  
libhttpd!ap_internal_redirect+36	  
mod_rewrite+545d	  
libhttpd!ap_run_handler+35	  
libhttpd!ap_invoke_handler+10f	  
libhttpd!ap_internal_redirect_handler+29a	  
libhttpd!ap_process_request+f	  
libhttpd!ap_byterange_filter+1581	  
libhttpd!ap_run_process_connection+35	  
libhttpd!ap_process_connection+45	  
libhttpd!ap_run_generate_log_id+3da0	  
kernel32!BaseThreadInitThunk+14	  
ntdll!RtlUserThreadStart+21
```

**Comment by dreamsxin** [comment]
I can't see the problem from this information. If I can reproduce it from linux, I can write different code to test it.

**Comment by hakimio** [comment]
@dreamsxin Have you tried to run Phalcon CLI TS with pthreads / multiple threads?

**Comment by CameronHall** [comment]
@hakimio I've just tested this myself on PHP 7.3 CLI TS on Apline Linux and can confirm (not with pthreads) that the issue is not reproducible. If you're interested in how I tested let me know and I'll create a repo.

Right now, I'm creating a Windows 10 VM on Azure for @dreamsxin to play with.

**Comment by hakimio** [comment]
@CameronHall it has to be multi-threaded app, because the issue is with thread-safety.

**Comment by CameronHall** [comment]
That would make sense. Apache would typically do that for us... does
someone have a sample multi-threaded app?

**Comment by CameronHall** [comment]
@dreamsxin I sent you an email yesterday with the details to access the VM.

**Comment by dreamsxin** [comment]
@CameronHall I will try.

**Comment by CameronHall** [comment]
@dreamsxin I believe the issue may haver to do with the [zephir_deinitialize_memory method](https://github.com/phalcon/zephir/blob/bf422be11873e51d383627a8d51d1b50645c9be6/kernels/ZendEngine3/memory.c#L348-397). Though I don't know enough about the PHP Internals to be sure. Do you have any ideas?

**Comment by dreamsxin** [comment]
Maybe double free the zval.

**Comment by dreamsxin** [comment]
Can't reproduce

- OS: Ubuntu 16
- PHP: 7.0-zts
- Zephir: 0.11.12
- Apache: Apache/2.4.18

- Server API | Apache 2.0 Handler
- Zend Extension Build | API320151012,TS
- PHP Extension Build | API20151012,TS

Zephir code:
```zephir
namespace Test;

class app
{
	public function __construct()
	{
		var di;
		let di = Di::getInstance();
	}
}
```
```zephir
namespace Test;

class Di
{
	private static _default;

	public static function getInstance()
	{
		var di;
		let di = self::_default;

		if !di {
			let di = new self();
			let self::_default = di;
		}

		return self::_default;
	}
}
```

**Comment by hakimio** [comment]
@dreamsxin didn't @CameronHall already provide you with a VM you can use for testing?

**Comment by dreamsxin** [comment]
I just had this problem with Phalcon 3.4, use Zephir/development regenerate code，the problem solving.
```shell
git clone https://github.com/dreamsxin/zephir.git
git fetch origin
git checkout origin/phalcon_3.4 -f

cd cphalcon-3.4
../zephir/zephir fullclean
../zephir/zephir generate
cd ext/
make -j4 && make install
```
test.php
```php
<?php
error_reporting(E_ALL);
ini_set('display_errors', true);
$di = new Phalcon\DI\FactoryDefault;
echo "ok".PHP_EOL;
```

```shell
ab -v2 -n 1000 -c 50 http://localhost/test.php
```

**Comment by sergeyklay** [comment]
Closing, this is fixed. If there are bugs, we can follow up in separate issues.
